version: '3.4'

services:
  providerdb:
    container_name: providerdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"      

  provider.api:
    container_name: provider.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProviderConnectionString=Server=providerdb;Database=ProviderDb;User Id=sa;Password=SwN12345678;MultipleActiveResultSets=true;TrustServerCertificate=True;"
    depends_on:
        - providerdb
    ports:
       - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  provider.grpc:
    container_name: provider.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProviderConnectionString=Server=providerdb;Database=ProviderDb;User Id=sa;Password=SwN12345678;MultipleActiveResultSets=true;TrustServerCertificate=True;"
   depends_on:
        - providerdb
    ports:
       - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
